version: '3'

services:
 mariadb:
  container_name: mariadb
  init: true
  networks:
   - inception
  build:
   context: requirements/mariadb
   dockerfile: Dockerfile
  env_file: .env
  volumes:
   - DB:/var/lib/mysql
  restart: unless-stopped

 nginx:
  container_name: nginx
  init: true
  networks:
   - inception
  depends_on:
   - wordpress
  build:
   context: requirements/nginx
   dockerfile: Dockerfile
  env_file: .env
  volumes:
   - WordPress:/var/www/html
  restart: on-failure
  ports :
   - "443:443"

 wordpress:
  container_name: wordpress
  init: true
  networks:
   - inception
  depends_on:
   - mariadb
   - redis
  build:
   context: requirements/wordpress
   dockerfile: Dockerfile
  env_file: .env
  volumes:
   - WordPress:/var/www/html
  restart: on-failure

 adminer:
  container_name: adminer
  init: true
  networks:
   - inception
  depends_on:
   - mariadb
   - wordpress
  build:
   context: bonus/adminer
   dockerfile: Dockerfile
  env_file: .env
  volumes:
   - WordPress:/var/www/html
  restart: on-failure

 website:
  container_name: website
  init: true
  networks:
   - inception
  build:
   context: bonus/website
   dockerfile: Dockerfile
  restart: on-failure
  ports :
   - "80:80"

 redis:
  container_name: redis
  init: true
  networks:
   - inception
  build:
   context: bonus/redis
   dockerfile: Dockerfile
  restart: on-failure

volumes:
 WordPress:
  driver: local
  driver_opts:
   type: 'none'
   o: 'bind'
   device: '/home/lcalvie/data/WordPress'
 DB:
  driver: local
  driver_opts:
   type: 'none'
   o: 'bind'
   device: '/home/lcalvie/data/DB'

networks:
    inception:
      driver: bridge

