version: '3'

services:
 mariadb:
  container_name: mariadb
  init: true
  networks:
   - inception
  build:
   context: requirements/mariadb
   dockerfile: Dockerfile
  env_file: .env
  volumes:
   - DB:/var/lib/mysql
  restart: unless-stopped

 nginx:
  container_name: nginx
  init: true
  networks:
   - inception
  depends_on:
    - wordpress
    - python
  build:
   context: requirements/nginx
   dockerfile: Dockerfile
  env_file: .env
  volumes:
   - WordPress:/var/www/html
   - Python:/var/www/python
  restart: on-failure
  ports :
   - "4443:443"
   - "9998:9998"

 wordpress:
  container_name: wordpress
  init: true
  networks:
   - inception
  depends_on:
   - mariadb
   - redis
  build:
   context: requirements/wordpress
   dockerfile: Dockerfile
  env_file: .env
  volumes:
   - WordPress:/var/www/html
  restart: on-failure

 adminer:
  container_name: adminer
  init: true
  networks:
   - inception
  depends_on:
   - mariadb
   - wordpress
  build:
   context: bonus/adminer
   dockerfile: Dockerfile
  env_file: .env
  volumes:
   - WordPress:/var/www/html
  restart: on-failure

 website:
  container_name: website
  init: true
  networks:
   - inception
  build:
   context: bonus/website
   dockerfile: Dockerfile
  restart: on-failure
  ports :
   - "9999:9999"

 redis:
  container_name: redis
  init: true
  networks:
   - inception
  build:
   context: bonus/redis
   dockerfile: Dockerfile
  restart: on-failure

 ftp:
  container_name: ftp
  init: true
  networks:
   - inception
  depends_on:
   - wordpress
  build:
   context: bonus/FTP
   dockerfile: Dockerfile
  env_file: .env
  restart: on-failure
  volumes:
   - WordPress:/var/www/html
  ports :
   - "2220:20"
   - "2221:21"
   - "4000-4200:4000-4200"

 python:
  container_name: python
  init: true
  networks:
   - inception
  build:
   context: bonus/python
   dockerfile: Dockerfile
  env_file: .env
  restart: on-failure
  volumes:
   - Python:/var/www/python

volumes:
 WordPress:
  driver: local
  driver_opts:
   type: 'none'
   o: 'bind'
   device: '${DATA_DIR}/WordPress'
 DB:
  driver: local
  driver_opts:
   type: 'none'
   o: 'bind'
   device: '${DATA_DIR}/DB'
 Python:
   driver: local
   driver_opts:
    type: 'none'
    o: 'bind'
    device: '${DATA_DIR}/Python'

networks:
    inception:
      driver: bridge

